export const districts = [
  {
    id: 1,
    name: "Ablekuma Central",
    abbrv: "ABCMA",
    regionId: 1,
  },
  {
    id: 2,
    name: "Ablekuma North",
    abbrv: "ABNMA",
    regionId: 1,
  },
  { id: 3, name: "Ablekuma West", abbrv: "ABWMA", regionId: 1 },
  { id: 4, name: "Accra Metropolitan", abbrv: "ACCMA", regionId: 1 },
  { id: 5, name: "Ada East", abbrv: "ADEMA", regionId: 1 },
  { id: 6, name: "Ada West", abbrv: "ADWMA", regionId: 1 },
  { id: 7, name: "Adenta", abbrv: "ADTMA", regionId: 1 },
  { id: 8, name: "Ashaiman", abbrv: "ASHMA", regionId: 1 },
  { id: 9, name: "Ayawaso Central", abbrv: "AYCMA", regionId: 1 },
  { id: 10, name: "Ayawaso East", abbrv: "AYEMA", regionId: 1 },
  { id: 11, name: "Ayawaso North", abbrv: "AYNMA", regionId: 1 },
  { id: 12, name: "Ayawaso West", abbrv: "AYWMA", regionId: 1 },
  { id: 13, name: "Ga Central", abbrv: "GACMA", regionId: 1 },
  { id: 14, name: "Ga East", abbrv: "GAEMA", regionId: 1 },

  { id: 15, name: "Ga North", abbrv: "GANMA", regionId: 1 },
  { id: 16, name: "Ga South", abbrv: "GASMA", regionId: 1 },
  { id: 17, name: "Ga West", abbrv: "GAWMA", regionId: 1 },
  { id: 18, name: "Korle-Klottey", abbrv: "KKLMA", regionId: 1 },
  { id: 19, name: "Kpone-Katamanso", abbrv: "KPKMA", regionId: 1 },
  { id: 20, name: "Krowor", abbrv: "KROMA", regionId: 1 },
  { id: 21, name: "La-Dade-Kotopon", abbrv: "LDKMA", regionId: 1 },
  { id: 22, name: "La-Nkwantanang-Madina", abbrv: "LNMMA", regionId: 1 },
  { id: 23, name: "Ledzokuku", abbrv: "LZKMA", regionId: 1 },

  { id: 24, name: "Ningo-Prampram", abbrv: "NGPMA", regionId: 1 },
  { id: 25, name: "Okaikwei North", abbrv: "OKNMA", regionId: 1 },
  { id: 26, name: "Shai-Osudoku", abbrv: "SHOMA", regionId: 1 },
  { id: 27, name: "Tema Metropolitan", abbrv: "TEMMA", regionId: 1 },
  { id: 28, name: "Tema West", abbrv: "TMWMA", regionId: 1 },
  { id: 29, name: "Weija Gbawe", abbrv: "WJGMA", regionId: 1 },
  { id: 30, name: "Gomoa East District", abbrv: "GMEDA", regionId: 1 },
  { id: 31, name: "Awutu Senya East Municipal", abbrv: "AWSEMA", regionId: 1 },

  // { name: "Adansi Asokwa", abbrv: "ADKMA", regionId: 2 },
  // { name: "Adansi North", abbrv: "ADNMA", regionId: 2 },
  // { name: "Adansi South", abbrv: "ADSMA", regionId: 2 },
  // { name: "Afigya-Kwabre North", abbrv: "AKNMA", regionId: 2 },
  // { name: "Afigya-Kwabre South", abbrv: "AFKSMA", regionId: 2 },
  // { name: "Ahafo-Ano North", abbrv: "AANMA", regionId: 2 },
  // { name: "Ahafo-Ano South East", abbrv: "ASEMA", regionId: 2 },
  // { name: "Ahafo-Ano South West", abbrv: "ASWMA", regionId: 2 },
  // { name: "Akrofuom", abbrv: "AKFMA", regionId: 2 },
  // { name: "Amansie Central", abbrv: "AMCDA", regionId: 2 },
  // { name: "Amansie West", abbrv: "AMWDA", regionId: 2 },
  // { name: "Amansie South", abbrv: "AMSDA", regionId: 2 },
  // { name: "Asante-Akim Central", abbrv: "AACMA", regionId: 2 },
  // { name: "Asante-Akim North", abbrv: "AANDA", regionId: 2 },
  // { name: "Asante-Akim South", abbrv: "AASDA", regionId: 2 },
  // { name: "Asokore-Mampong", abbrv: "ASMDA", regionId: 2 },
  // { name: "Asokwa", abbrv: "ASKMA", regionId: 2 },
  // { name: "Atwima-Kwanwoma", abbrv: "ATKMA", regionId: 2 },
  // { name: "Atwima-Mponua", abbrv: "ATMMA", regionId: 2 },
  // { name: "Atwima-Nwabiagya", abbrv: "ATNMA", regionId: 2 },
  // { name: "Atwima-Nwabiagya North", abbrv: "ANNMA", regionId: 2 },
  // { name: "Bekwai", abbrv: "BEKMA", regionId: 2 },
  // { name: "Bosome Freho", abbrv: "BSFMA", regionId: 2 },
  // { name: "Bosomtwe", abbrv: "BSTMA", regionId: 2 },
  // { name: "Ejisu", abbrv: "EJSMA", regionId: 2 },
  // { name: "Ejura/Sekyedumase", abbrv: "EJRMA", regionId: 2 },
  // { name: "Juaben", abbrv: "JBNMA", regionId: 2 },
  // { name: "Kumasi", abbrv: "KSIMA", regionId: 2 },
  // { name: "Kwabre East", abbrv: "KWEMA", regionId: 2 },
  // { name: "Kwadaso", abbrv: "KWDMA", regionId: 2 },
  // { name: "Mampong", abbrv: "MPGMA", regionId: 2 },
  // { name: "Obuasi East", abbrv: "OBEMA", regionId: 2 },
  // { name: "Obuasi", abbrv: "OBSMA", regionId: 2 },
  // { name: "Offinso", abbrv: "OFSMA", regionId: 2 },
  // { name: "Offinso North", abbrv: "OFNMA", regionId: 2 },
  // { name: "Oforikrom", abbrv: "OFKMA", regionId: 2 },
  // { name: "Old Tafo", abbrv: "OTFMA", regionId: 2 },
  // { name: "Sekyere Afram Plains", abbrv: "SAPMA", regionId: 2 },
  // { name: "Sekyere Central", abbrv: "SYCMA", regionId: 2 },
  // { name: "Sekyere East", abbrv: "SYEMA", regionId: 2 },
  // { name: "Sekyere Kumawu", abbrv: "SYKMA", regionId: 2 },
  // { name: "Sekyere South", abbrv: "SYSMA", regionId: 2 },
  // { name: "Suame", abbrv: "SMEMA", regionId: 2 },

  // { name: "Banda District", abbrv: "BADA", regionId: 3 },
  // { name: "Berekum East", abbrv: "BREDA", regionId: 3 },
  // { name: "Dormaa Central Municipal", abbrv: "DCMA", regionId: 3 },
  // { name: "Dormaa East District", abbrv: "DREDA", regionId: 3 },
  // { name: "Dormaa West District", abbrv: "DRWDA", regionId: 3 },
  // { name: "Jaman North District", abbrv: "JMNDA", regionId: 3 },
  // { name: "Jaman South Municipal", abbrv: "JMSDA", regionId: 3 },
  // { name: "Sunyani Municipal", abbrv: "SYIMA", regionId: 3 },
  // { name: "Sunyani West Municipal", abbrv: "SYWMA", regionId: 3 },
  // { name: "Tain District", abbrv: "TANDA", regionId: 3 },
  // { name: "Wenchi Municipal", abbrv: "WCHMA", regionId: 3 },
  // { name: "Berekum West District", abbrv: "BRWDA", regionId: 3 },

  // { name: "Atebubu Amantin Municipal", abbrv: "AAMA", regionId: 4 },
  // { name: "Kintampo North Municipal", abbrv: "KTNMA", regionId: 4 },
  // { name: "Kintampo South District", abbrv: "KTSDA", regionId: 4 },
  // { name: "Nkoranza South Municipal", abbrv: "NKZSMA", regionId: 4 },
  // { name: "Nkoranza North District", abbrv: "NKZNMA", regionId: 4 },
  // { name: "Pru East District", abbrv: "PREDA", regionId: 4 },
  // { name: "Sene East District", abbrv: "SNEDA", regionId: 4 },
  // { name: "Sene West District", abbrv: "SNWDA", regionId: 4 },
  // { name: "Techiman Municipal", abbrv: "TCMMA", regionId: 4 },
  // { name: "Techiman North District", abbrv: "TCNDA", regionId: 4 },
  // { name: "Pru West District", abbrv: "PRWDA", regionId: 4 },

  // { name: "Abura Asebu Kwamankese District", abbrv: "AAKDA", regionId: 5 },
  // { name: "Agona East District", abbrv: "AGETDA", regionId: 5 },
  // { name: "Agona West Municipal", abbrv: "AGWDA", regionId: 5 },
  // { name: "Ajumako Enyan Essiam District", abbrv: "AEEDA", regionId: 5 },
  // { name: "Asikuma Odoben Brankwa District", abbrv: "AOBDA", regionId: 5 },
  // { name: "Assin Foso Municipal", abbrv: "ASFMA", regionId: 5 },
  // { name: "Assin South District", abbrv: "ASSDA", regionId: 5 },
  // { name: "Awutu Senya West District", abbrv: "ASWDA", regionId: 5 },
  // { name: "Cape Coast Metropolitan", abbrv: "CCMA", regionId: 5 },
  // { name: "Effutu Municipal", abbrv: "EFFMA", regionId: 5 },
  // { name: "Ekumfi District", abbrv: "EKFDA", regionId: 5 },
  // { name: "Gomoa Central District", abbrv: "GOCDA", regionId: 5 },
  // { name: "Gomoa West District", abbrv: "GOWDA", regionId: 5 },
  // {
  //   name: "Komenda Edina Eguafo Abirem Municipal",
  //   abbrv: "KEEAMA",
  //   regionId: 5,
  // },
  // { name: "Mfantseman Municipal", abbrv: "MFMMA", regionId: 5 },
  // { name: "Twifo Atti Morkwa District", abbrv: "TAMDA", regionId: 5 },
  // { name: "Twifo Heman Lower Denkyira District", abbrv: "THLDDA", regionId: 5 },
  // { name: "Upper Denkyira East Municipal", abbrv: "UDEMA", regionId: 5 },
  // { name: "Upper Denkyira West District", abbrv: "UDWDA", regionId: 5 },
  // { name: "Assin North District", abbrv: "ASNDA", regionId: 5 },

  // { name: "Akuapem North Municipal", abbrv: "AKWNMA", regionId: 6 },
  // { name: "Akwapim South District", abbrv: "AKWSMA", regionId: 6 },
  // { name: "Akyemansa District", abbrv: "AKDA", regionId: 6 },
  // { name: "Asuogyaman District", abbrv: "ASDA", regionId: 6 },
  // { name: "Atiwa West District", abbrv: "ATWDA", regionId: 6 },
  // { name: "Ayensuano District", abbrv: "AYDA", regionId: 6 },
  // { name: "Birim Central Municipal", abbrv: "BRCMA", regionId: 6 },
  // { name: "Birim North District", abbrv: "BRNDA", regionId: 6 },
  // { name: "Birim South District", abbrv: "BRSDA", regionId: 6 },
  // { name: "Denkyembour District", abbrv: "DKBDA", regionId: 6 },
  // { name: "Abuakwa South Municipal", abbrv: "ABSMA", regionId: 6 },
  // { name: "Fanteakwa North District", abbrv: "FTNDA", regionId: 6 },
  // { name: "Kwaebibirem Municipal", abbrv: "KBMA", regionId: 6 },
  // { name: "Kwahu Afram Plains North District", abbrv: "KAPNDA", regionId: 6 },
  // { name: "Kwahu Afram Plains South District", abbrv: "KAPSDA", regionId: 6 },
  // { name: "Kwahu East District", abbrv: "KWEDA", regionId: 6 },
  // { name: "Kwahu South Municipal", abbrv: "KWSMA", regionId: 6 },
  // { name: "Kwahu West Municipal", abbrv: "KWWMA", regionId: 6 },
  // { name: "Lower Manya Krobo Municipal", abbrv: "LMKMA", regionId: 6 },
  // { name: "New Juaben South Municipal", abbrv: "NJSMA", regionId: 6 },
  // { name: "Nsawam Adoagyiri Municipal", abbrv: "NSAMA", regionId: 6 },
  // { name: "Suhum Municipal", abbrv: "SUHMA", regionId: 6 },
  // { name: "Upper Manya Krobo District", abbrv: "UMKDA", regionId: 6 },
  // { name: "Upper West Akim District", abbrv: "UWADA", regionId: 6 },
  // { name: "West Akim Municipal", abbrv: "WSAMA", regionId: 6 },
  // { name: "Yilo Krobo Municipal", abbrv: "YIKMA", regionId: 6 },
  // { name: "Okere District", abbrv: "OKDA", regionId: 6 },
  // { name: "Atiwa East District", abbrv: "ATEDA", regionId: 6 },
  // { name: "Fanteakwa South District", abbrv: "FTSDA", regionId: 6 },
  // { name: "Asene Manso Akroso District", abbrv: "AMADA", regionId: 6 },
  // { name: "Abuakwa North Municipal", abbrv: "ABKNMA", regionId: 6 },
  // { name: "New Juaben North Municipal", abbrv: "NJNMA", regionId: 6 },
  // { name: "Achiase District", abbrv: "ACHDA", regionId: 6 },

  // { name: "Asunafo North Municipal", abbrv: "ASNMA", regionId: 7 },
  // { name: "Asunafo South District", abbrv: "ASNSDA", regionId: 7 },
  // { name: "Asutifi North District", abbrv: "ATNDA", regionId: 7 },
  // { name: "Asutifi South District", abbrv: "ATSDA", regionId: 7 },
  // { name: "Tano North Municipal", abbrv: "TNNMA", regionId: 7 },
  // { name: "Tano South Municipal", abbrv: "TNSMA", regionId: 7 },

  // { name: "Bunkpurugu Nyankpanduri District", abbrv: "BKNDA", regionId: 8 },
  // { name: "Chereponi District", abbrv: "CHDA", regionId: 8 },
  // { name: "East Mamprusi Municipal", abbrv: "EMMA", regionId: 8 },
  // { name: "Mamprugu Moagduri District", abbrv: "MMDA", regionId: 8 },
  // { name: "West Mamprusi Municipal", abbrv: "WEMMA", regionId: 8 },
  // { name: "Yunyoo-Nasuan District", abbrv: "YNNDA", regionId: 8 },

  // { name: "Gushegu Municipal", abbrv: "GSHMA", regionId: 9 },
  // { name: "Karaga District", abbrv: "KRGDA", regionId: 9 },
  // { name: "Kpandai District", abbrv: "KPDDA", regionId: 9 },
  // { name: "Kumbungu District", abbrv: "KMBDA", regionId: 9 },
  // { name: "Mion District", abbrv: "MINDA", regionId: 9 },
  // { name: "Nanumba North Municipal", abbrv: "NANMA", regionId: 9 },
  // { name: "Nanumba South District", abbrv: "NNSDA", regionId: 9 },
  // { name: "Saboba District", abbrv: "SABDA", regionId: 9 },
  // { name: "Sagnarigu Municipal", abbrv: "SGNMA", regionId: 9 },
  // { name: "Savelugu Municipal", abbrv: "SVGMA", regionId: 9 },
  // { name: "Tamale Metropolitan", abbrv: "TMLMA", regionId: 9 },
  // { name: "Tatale/Sanguli District", abbrv: "TTSDA", regionId: 9 },
  // { name: "Tolon District", abbrv: "TLNDA", regionId: 9 },
  // { name: "Yendi Municipal", abbrv: "YDMA", regionId: 9 },
  // { name: "Zabzugu District", abbrv: "ZBZDA", regionId: 9 },
  // { name: "Nanton District", abbrv: "MTNDA", regionId: 9 },

  // { name: "Biakoye District", abbrv: "BKYDA", regionId: 10 },
  // { name: "Jasikan District", abbrv: "JSKDA", regionId: 10 },
  // { name: "Kadjebi District", abbrv: "KJBDA", regionId: 10 },
  // { name: "Krachi East Municipal", abbrv: "KREMA", regionId: 10 },
  // { name: "Krachi Nchumuru District", abbrv: "KRNDA", regionId: 10 },
  // { name: "Krachi West District", abbrv: "KRWDA", regionId: 10 },
  // { name: "Nkwanta North District", abbrv: "NKNDA", regionId: 10 },
  // { name: "Nkwanta South Municipal", abbrv: "NKSMA", regionId: 10 },
  // { name: "Guan District", abbrv: "GUNDA", regionId: 10 },

  // { name: "Bole District", abbrv: "BLEDA", regionId: 11 },
  // { name: "Central Gonja District", abbrv: "CTGDA", regionId: 11 },
  // { name: "East Gonja Municipal", abbrv: "ETGMA", regionId: 11 },
  // { name: "North Gonja District", abbrv: "NTGDA", regionId: 11 },
  // { name: "Sawla-Tuna-Kalba District", abbrv: "STKDA", regionId: 11 },
  // { name: "West Gonja Municipal", abbrv: "WGJMA", regionId: 11 },
  // { name: "North East Gonja Municipal", abbrv: "NEGMA", regionId: 11 },

  // { name: "Daffiama Bussie Issa District", abbrv: "DBIDA", regionId: 12 },
  // { name: "Jirapa Municipal", abbrv: "JRPMA", regionId: 12 },
  // { name: "Lambussie Karni District", abbrv: "LBKDA", regionId: 12 },
  // { name: "Lawra Municipal", abbrv: "LWRMA", regionId: 12 },
  // { name: "Nadowli Kaleo District", abbrv: "NDKDA", regionId: 12 },
  // { name: "Nandom Municipal", abbrv: "NDMMA", regionId: 12 },
  // { name: "Sissala East Municipal", abbrv: "SLEMA", regionId: 12 },
  // { name: "Sissala West District", abbrv: "SLWDA", regionId: 12 },
  // { name: "Wa East District", abbrv: "WETDA", regionId: 12 },
  // { name: "Wa Municipal", abbrv: "WAMA", regionId: 12 },

  // { name: "Bawku Municipal", abbrv: "BWKMA", regionId: 13 },
  // { name: "Bawku West District", abbrv: "BKWDA", regionId: 13 },
  // { name: "Binduri District", abbrv: "BDRDA", regionId: 13 },
  // { name: "Bolgatanga Municipal", abbrv: "BTGMA", regionId: 13 },
  // { name: "Bongo District", abbrv: "BNGDA", regionId: 13 },
  // { name: "Builsa North Municipal", abbrv: "BLNMA", regionId: 13 },
  // { name: "Builsa South District", abbrv: "BLSMA", regionId: 13 },
  // { name: "Garu District", abbrv: "GRUDA", regionId: 13 },
  // { name: "Kassena Nankana Municipal", abbrv: "KSNMA", regionId: 13 },
  // { name: "Kassena Nankana West District", abbrv: "KNWDA", regionId: 13 },
  // { name: "Nabdam District", abbrv: "NBMDA", regionId: 13 },
  // { name: "Pusiga District", abbrv: "PSGDA", regionId: 13 },
  // { name: "Talensi District", abbrv: "TLSDA", regionId: 13 },
  // { name: "Bolgatanga East District", abbrv: "BGEDA", regionId: 13 },
  // { name: "Tempane District", abbrv: "TPNDA", regionId: 13 },

  // { name: "Adaklu District", abbrv: "ADKDA", regionId: 14 },
  // { name: "Afadzato South District", abbrv: "AZSDA", regionId: 14 },
  // { name: "Agotime Ziope District", abbrv: "AGZDA", regionId: 14 },
  // { name: "Akatsi North District", abbrv: "AKNDA", regionId: 14 },
  // { name: "Akatsi South Municipal", abbrv: "AKTSMA", regionId: 14 },
  // { name: "Central Tongu District", abbrv: "CTTDA", regionId: 14 },
  // { name: "Ho Municipal", abbrv: "HOMA", regionId: 14 },
  // { name: "Ho West District", abbrv: "HOWDA", regionId: 14 },
  // { name: "Hohoe Municipal", abbrv: "HHMA", regionId: 14 },
  // { name: "Keta Municipal", abbrv: "KTAMA", regionId: 14 },
  // { name: "Ketu North Municipal", abbrv: "KETNMA", regionId: 14 },
  // { name: "Ketu South Municipal", abbrv: "KTSMA", regionId: 14 },
  // { name: "Kpando Municipal", abbrv: "KPDMA", regionId: 14 },
  // { name: "North Dayi District", abbrv: "NTDDA", regionId: 14 },
  // { name: "North Tongu District", abbrv: "NTTDA", regionId: 14 },
  // { name: "South Dayi District", abbrv: "STDDA", regionId: 14 },
  // { name: "South Tongu District", abbrv: "STTDA", regionId: 14 },
  // { name: "Anloga District", abbrv: "ALGDA", regionId: 14 },

  // { name: "Ahanta West Municipal", abbrv: "AHWMA", regionId: 15 },
  // { name: "Amenfi Central District", abbrv: "AFCDA", regionId: 15 },
  // { name: "Wassa Amenfi East Municipal", abbrv: "WAEMA", regionId: 15 },
  // { name: "Wassa Amenfi West Municipal", abbrv: "WAWMA", regionId: 15 },
  // { name: "Ellembelle District", abbrv: "ELBDA", regionId: 15 },
  // { name: "Jomoro Municipal", abbrv: "JMRMA", regionId: 15 },
  // { name: "Mpohor District", abbrv: "MPHDA", regionId: 15 },
  // { name: "Nzema East Municipal", abbrv: "NZEMA", regionId: 15 },
  // { name: "Prestea-Huni Valley Municipal", abbrv: "PHVMA", regionId: 15 },
  // { name: "Sekondi Takoradi Metropolitan", abbrv: "SKTMA", regionId: 15 },
  // { name: "Shama District", abbrv: "SHMDA", regionId: 15 },
  // { name: "Tarkwa Nsuaem Municipal", abbrv: "TKNMA", regionId: 15 },
  // { name: "Wassa East District", abbrv: "WSEDA", regionId: 15 },
  // { name: "Effia Kwesimintsim Municipal", abbrv: "EFKMA", regionId: 15 },

  // { name: "Aowin Municipal", abbrv: "AWNMA", regionId: 16 },
  // { name: "Bia East District", abbrv: "BIEDA", regionId: 16 },
  // { name: "Bia West District", abbrv: "BIWDA", regionId: 16 },
  // { name: "Bibiani-Anhwiaso Bekwai Municipal", abbrv: "BABMA", regionId: 16 },
  // { name: "Bodi District", abbrv: "BDIDA", regionId: 16 },
  // { name: "Juaboso District", abbrv: "JBSDA", regionId: 16 },
  // { name: "Sefwi Akontombra District", abbrv: "SFADA", regionId: 16 },
  // { name: "Sefwi Wiawso Municipal", abbrv: "SFWMA", regionId: 16 },
  // { name: "Suaman District", abbrv: "SMNDA", regionId: 16 },
];
