const { District } = require('../models')

exports.seedDistrict = async () => {

    await District.create({ id: 1, regionId: 1, districtName: 'ABLEKUMA CENTRAL MUNICIPALITY' })
    await District.create({ id: 2, regionId: 1, districtName: 'ABLEKUMA NORTH MUNICIPALITY' })
    await District.create({ id: 3, regionId: 1, districtName: 'ABLEKUMA WEST MUNICIPALITY' })
    await District.create({ id: 4, regionId: 1, districtName: 'ACCRA METROPOLITAN' })
    await District.create({ id: 5, regionId: 1, districtName: 'ADA EAST MUNICIPALITY' })
    await District.create({ id: 6, regionId: 1, districtName: 'ADA WEST MUNICIPALITY' })
    await District.create({ id: 7, regionId: 1, districtName: 'ADENTAN MUNICIPALITY' })
    await District.create({ id: 8, regionId: 1, districtName: 'ASHAIMAN MUNICIPALITY' })
    await District.create({ id: 9, regionId: 1, districtName: 'AYAWASO CENTRAL MUNICIPALITY' })
    await District.create({ id: 10, regionId: 1, districtName: 'AYAWASO EAST MUNICIPALITY' })
    await District.create({ id: 11, regionId: 1, districtName: 'AYAWASO NORTH MUNICIPALITY' })
    await District.create({ id: 12, regionId: 1, districtName: 'AYAWASO WEST MUNICIPALITY' })
    await District.create({ id: 13, regionId: 1, districtName: 'GA CENTRAL MUNICIPALITY' })
    await District.create({ id: 14, regionId: 1, districtName: 'GA EAST MUNICIPALITY' })
    await District.create({ id: 15, regionId: 1, districtName: 'GA NORTH MUNICIPALITY' })
    await District.create({ id: 16, regionId: 1, districtName: 'GA SOUTH MUNICIPALITY' })
    await District.create({ id: 17, regionId: 1, districtName: 'GA WEST MUNICIPALITY' })
    await District.create({ id: 18, regionId: 1, districtName: 'KORLE KLOTTEY MUNICIPALITY' })
    await District.create({ id: 19, regionId: 1, districtName: 'KPONE KATAMANSO MUNICIPALITY' })
    await District.create({ id: 20, regionId: 1, districtName: 'KROWOR MUNICIPALITY' })
    await District.create({ id: 21, regionId: 1, districtName: 'LA DADE KOTOPON MUNICIPALITY' })
    await District.create({ id: 22, regionId: 1, districtName: 'LEDZOKUKU MUNICIPALITY' })
    await District.create({ id: 23, regionId: 1, districtName: 'NINGO PRAMPRAM MUNICIPALITY' })
    await District.create({ id: 24, regionId: 1, districtName: 'OKAIKWEI NORTH MUNICIPALITY' })
    await District.create({ id: 25, regionId: 1, districtName: 'OKAIKWEI SOUTH MUNICIPALITY' })
    await District.create({ id: 26, regionId: 1, districtName: 'OSU KLOTTEY MUNICIPALITY' })
    await District.create({ id: 27, regionId: 1, districtName: 'TEMA METROPOLITAN' })
    await District.create({ id: 28, regionId: 1, districtName: 'TEMA WEST MUNICIPALITY' })
    await District.create({ id: 29, regionId: 1, districtName: 'WEIJA-GBAWE MUNICIPALITY' })
    await District.create({ id: 30, regionId: 1, districtName: 'SHAI OSU DOKU MUNICIPALITY' })
    await District.create({ id: 31, regionId: 1, districtName: 'LA NKWANTANAN MUNICIPALITY' })

}
